general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

# [window]
# opacity = 0.94

[font]
size = 12

[font.normal]
family ="Hack Nerd Font Mono"
# style = "Bold"

[env]
TERM = "xterm-256color"
